server:
  port: "8080"
  read_timeout: "15s"
  write_timeout: "15s"
  idle_timeout: "60s"

database:
  type: "sqlite" # Options: memory, sqlite, postgres
  sqlite:
    path: "./data/dove.db"
  postgres:
    url: "postgres://dove:dove@localhost:5432/dove?sslmode=disable"

cache:
  enabled: true
  redis:
    url: "redis://localhost:6379"
    password: ""
    db: 0
    pool_size: 10
    min_idle_conns: 5
    max_retries: 3
    read_timeout: "3s"
    write_timeout: "3s"
  ttl: "10m" # Cache TTL for URL entries

app:
  base_url: "http://localhost:8080"
  short_code_length: 6

logging:
  level: "debug"

metrics:
  enabled: true
  path: "/metrics"
  namespace: "dove"
  subsystem: "urlshortener"
  collect_runtime: true
  collect_database: true
  collect_cache: true
