global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Dove application metrics
  - job_name: 'dove'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          service: 'dove'
          environment: 'development'
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Scrape Redis exporter (if added in future)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
        labels:
          service: 'redis'
          environment: 'development'

  # Scrape PostgreSQL exporter (if added in future)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
        labels:
          service: 'postgres'
          environment: 'development'
