global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape Dove application metrics
  - job_name: 'dove'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          service: 'dove'
          environment: 'development'
    metrics_path: '/metrics'
    scrape_interval: 10s
